CLASS zafr_alta_direcciones DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zafr_alta_direcciones IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.
         DATA: IT_Direccion TYPE STANDARD TABLE OF zt11tt_direccion.
           IT_Direccion = VALUE #(
            ( CveDir = '401000000'  Direccion = 'COORDINACION DE REGIDURIAS              ' )
            ( CveDir = '401010000'  Direccion = 'DIRECCIÓN OPERATIVA                     ' )
            ( CveDir = '401010001'  Direccion = 'UNIDAD JURÍDICA                         ' )
            ( CveDir = '401010002'  Direccion = 'UNIDAD DE COMUNICACIÓN SOCIAL           ' )
            ( CveDir = '401010003'  Direccion = 'UNIDAD DE APOYO LOGÍSTICO               ' )
            ( CveDir = '402000000'  Direccion = 'OFICINA DE PRESIDENCIA                  ' )
            ( CveDir = '402010000'  Direccion = 'JEFATURA DE PRESIDENCIA                 ' )
            ( CveDir = '402020000'  Direccion = 'SECRETARÍA PRIVADA.                     ' )
            ( CveDir = '402030000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '402030100'  Direccion = 'DIRECCIÓN DE AGENDA                     ' )
            ( CveDir = '402030200'  Direccion = 'DIRECCIÓN DE RELACIONES PÚBLICAS        ' )
            ( CveDir = '402030300'  Direccion = 'DIRECCIÓN DE GIRAS Y LOGÍSTICA          ' )
            ( CveDir = '402040000'  Direccion = 'SECRETARÍA EJECUTIVA                    ' )
            ( CveDir = '402040100'  Direccion = 'DIRECCIÓN DE ATENCIÓN CIUDADANA         ' )
            ( CveDir = '402040200'  Direccion = 'DIR.DE VINCULACIÓN Y COORDINACIÓN INSTIT' )
            ( CveDir = '402040300'  Direccion = 'DIRECCIÓN DE GOBERNANZA REGULATORIA     ' )
            ( CveDir = '402050000'  Direccion = 'CONSEJERÍA JURÍDICA                     ' )
            ( CveDir = '402050100'  Direccion = 'DIRECCIÓN DE ESTUDIOS NORMATIVOS        ' )
            ( CveDir = '402050200'  Direccion = 'DIR.DE ANÁLISIS LEGAL SUPERVISIÓN Y VINC' )
            ( CveDir = '403000000'  Direccion = 'SINDICATURA MUNICIPAL                   ' )
            ( CveDir = '403010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '403020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '403030000'  Direccion = 'DIRECCIÓN GENERAL JURÍDICA              ' )
            ( CveDir = '403030100'  Direccion = 'DIRECCIÓN DE LO CONTENCIOSO             ' )
            ( CveDir = '403030200'  Direccion = 'DIRECCIÓN DE DERECHOS HUMANOS           ' )
            ( CveDir = '403040000'  Direccion = 'DIRECCIÓN CONSULTIVA                    ' )
            ( CveDir = '403050000'  Direccion = 'DIRECCIÓN DE JUZGADOS DE JUSTICIA CÍVICA' )
            ( CveDir = '403060000'  Direccion = 'DIR.DE MEDIACIÓN CONCILIACIÓN Y A.CONDOM' )
            ( CveDir = '404000000'  Direccion = 'SECRETARÍA DEL AYUNTAMIENTO             ' )
            ( CveDir = '404010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '404020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '404030000'  Direccion = 'DIRECCIÓN DE ARCHIVO GENERAL MUNICIPAL  ' )
            ( CveDir = '404040000'  Direccion = 'DIRECCIÓN DE BIENES PATRIMONIALES       ' )
            ( CveDir = '404060000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '404070000'  Direccion = 'TRIBUNAL DE CONCILIACIÓN Y ARBITRAJE DEL' )
            ( CveDir = '405000000'  Direccion = 'TESORERÍA MUNICIPAL                     ' )
            ( CveDir = '405010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '405020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '405030000'  Direccion = 'DIRECCIÓN GENERAL DE INGRESOS           ' )
            ( CveDir = '405030100'  Direccion = 'DIRECCIÓN DE INGRESOS                   ' )
            ( CveDir = '405030200'  Direccion = 'DIRECCIÓN DE CATASTRO                   ' )
            ( CveDir = '405040000'  Direccion = 'DIRECCIÓN GENERAL DE EGRESOS            ' )
            ( CveDir = '405040100'  Direccion = 'DIRECCIÓN DE EGRESOS Y CONTROL PRESUPUES' )
            ( CveDir = '405040200'  Direccion = 'DIRECCIÓN DE CONTABILIDAD               ' )
            ( CveDir = '405050000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '405060000'  Direccion = 'UNIDAD DE NORMATIVA Y REGULACIÓN COMERCI' )
            ( CveDir = '406000000'  Direccion = 'CONTRALORÍA MUNICIPAL                   ' )
            ( CveDir = '406010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '406020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '406030000'  Direccion = 'SUBCONTRALORÍA DE AUDITORÍA A OBRA Y SER' )
            ( CveDir = '406040000'  Direccion = 'SUBCONTRALORÍA DE AUDITORÍA CONTABLE Y F' )
            ( CveDir = '406050000'  Direccion = 'SUBCONTRALORÍA DE COMBATE A LA CORRUPCIÓ' )
            ( CveDir = '406060000'  Direccion = 'SUBCONTRALORÍA DE RESPONSABILIDADES     ' )
            ( CveDir = '406070000'  Direccion = 'SUBCONTRALORÍA DE MEJORA DE LA GESTIÓN  ' )
            ( CveDir = '406080000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '407000000'  Direccion = 'SECRETARÍA GENERAL DE GOBIERNO          ' )
            ( CveDir = '407010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '407020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '407030000'  Direccion = 'SUBSEC.DE DESARROLLO POLÍTICO Y SOC-TERR' )
            ( CveDir = '407030100'  Direccion = 'DIRECCIÓN DE FORTALECIMIENTO POLÍTICO   ' )
            ( CveDir = '407030200'  Direccion = 'DIRECCIÓN DE ORGANIZACIÓN TERRITORIAL   ' )
            ( CveDir = '407040000'  Direccion = 'SUBSECRETARÍA DE GOBIERNO               ' )
            ( CveDir = '407040100'  Direccion = 'DIRECCIÓN DE GOBERNABILIDAD             ' )
            ( CveDir = '407040200'  Direccion = 'DIRECCIÓN DE GOBERNANZA                 ' )
            ( CveDir = '407050000'  Direccion = 'SUBSECRETARÍA DE ABASTECIMIENTOS        ' )
            ( CveDir = '407050100'  Direccion = 'DIRECCIÓN DE VÍA PÚBLICA                ' )
            ( CveDir = '407050200'  Direccion = 'DIRECCIÓN DE MERCADOS                   ' )
            ( CveDir = '407060000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '408000000'  Direccion = 'SEC.DE BIENESTAR Y PARTICIPACIÓN CIUDADA' )
            ( CveDir = '408010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '408020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '408030000'  Direccion = 'SUBSECRETARÍA DE BIENESTAR SOCIAL       ' )
            ( CveDir = '408030100'  Direccion = 'DIRECCIÓN DE POLÍTICA SOCIAL            ' )
            ( CveDir = '408030200'  Direccion = 'DIRECCIÓN DE PROGRAMAS SOCIALES         ' )
            ( CveDir = '408040000'  Direccion = 'SUBSEC.DE DESARROLLO PROMOCIÓN Y VINC.CI' )
            ( CveDir = '408040100'  Direccion = 'DIRECCIÓN DE VINCULACIÓN SOCIAL         ' )
            ( CveDir = '408040200'  Direccion = 'DIR.DE PROMOCIÓN Y DESARROLLO SOCIAL    ' )
            ( CveDir = '408050000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '409000000'  Direccion = 'SECRETARÍA DE MOVILIDAD E INFRAESTRUCTUR' )
            ( CveDir = '409010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '409020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '409030000'  Direccion = 'SUBSECRETARÍA DE INFRAESTRUCTURA        ' )
            ( CveDir = '409030100'  Direccion = 'DIRECCIÓN DE OBRAS PÚBLICAS             ' )
            ( CveDir = '409030200'  Direccion = 'DIRECCIÓN DE CONTROL DE INVERSIÓN       ' )
            ( CveDir = '409040000'  Direccion = 'DIR.GENERAL DE PLANEACIÓN Y PROYECTOS   ' )
            ( CveDir = '409040100'  Direccion = 'DIRECCIÓN DE PLANEACIÓN Y PROYECTOS     ' )
            ( CveDir = '409040200'  Direccion = 'DIRECCIÓN DE LICITACIONES               ' )
            ( CveDir = '409050000'  Direccion = 'SUBSECRETARÍA MOVILIDAD Y SEGURIDAD VIAL' )
            ( CveDir = '409050100'  Direccion = 'DIRECCIÓN DE MOVILIDAD URBANA SUSTENTABL' )
            ( CveDir = '409050200'  Direccion = 'DIRECCIÓN DE SEGURIDAD VIAL             ' )
            ( CveDir = '409060000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '410000000'  Direccion = 'SECRETARÍA DE GESTIÓN Y DESARROLLO URBAN' )
            ( CveDir = '410010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '410020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '410030000'  Direccion = 'DIRECCIÓN DE DESARROLLO URBANO          ' )
            ( CveDir = '410040000'  Direccion = 'DIRECCIÓN DE NORMATIVIDAD AMBIENTAL E IM' )
            ( CveDir = '410050000'  Direccion = 'DIRECCIÓN DE GESTIÓN DE RIESGOS EN MATER' )
            ( CveDir = '410060000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '410070000'  Direccion = 'GERENCIA DEL CENTRO HISTÓRICO Y PATRIMON' )
            ( CveDir = '411000000'  Direccion = 'SECRETARÍA DE ECONOMÍA Y TURISMO        ' )
            ( CveDir = '411010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '411020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '411030000'  Direccion = 'DIRECCIÓN DE COMPETITIVIDAD Y DESARROLLO' )
            ( CveDir = '411040000'  Direccion = 'DIRECCIÓN DE VINCULACIÓN Y ECONOMÍA SOCI' )
            ( CveDir = '411050000'  Direccion = 'DIRECCIÓN DE TURISMO                    ' )
            ( CveDir = '411060000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '412000000'  Direccion = 'SECRETARÍA DE ADMINISTRACIÓN Y TECNOLOGÍ' )
            ( CveDir = '412010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '412020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '412030000'  Direccion = 'DIRECCIÓN GENERAL DE ADMINISTRACIÓN     ' )
            ( CveDir = '412030100'  Direccion = 'DIRECCIÓN DE RECURSOS MATERIALES Y SERVI' )
            ( CveDir = '412030200'  Direccion = 'DIRECCIÓN DE ADJUDICACIONES             ' )
            ( CveDir = '412030300'  Direccion = 'DIRECCIÓN DE PLANEACIÓN Y VINCULACIÓN AD' )
            ( CveDir = '412040000'  Direccion = 'DIRECCIÓN GENERAL DE DESARROLLO Y FORMAC' )
            ( CveDir = '412040100'  Direccion = 'DIRECCIÓN PARA LA ADMINISTRACIÓN DEL PER' )
            ( CveDir = '412040200'  Direccion = 'DIRECCIÓN DE SELECCIÓN, CAPACITACIÓN Y F' )
            ( CveDir = '412050000'  Direccion = 'DIRECCIÓN GENERAL DE GOBIERNO ELECTRÓNIC' )
            ( CveDir = '412050100'  Direccion = 'DIRECCIÓN DE SISTEMAS                   ' )
            ( CveDir = '412050200'  Direccion = 'DIRECCIÓN DE INFRAESTRUCTURA TECNOLÓGICA' )
            ( CveDir = '412060000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '413000000'  Direccion = 'SECRETARÍA DE SEGURIDAD CIUDADANA       ' )
            ( CveDir = '413010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '413020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '413030000'  Direccion = 'SUBSECRETARÍA DE OPERATIVIDAD POLICIAL  ' )
            ( CveDir = '413030100'  Direccion = 'DIRECCIÓN GENERAL DE DESPLIEGUE TERRITOR' )
            ( CveDir = '413030200'  Direccion = 'DIRECCIÓN GENERAL DE GRUPOS ESPECIALES Y' )
            ( CveDir = '413030201'  Direccion = 'DIRECCIÓN DE GRUPOS ESPECIALES          ' )
            ( CveDir = '413030202'  Direccion = 'DIRECCIÓN DE LOGÍSTICA OPERATIVA        ' )
            ( CveDir = '413040000'  Direccion = 'SUBSECRETARÍA DE INTELIGENCIA           ' )
            ( CveDir = '413040100'  Direccion = 'DIRECCIÓN GENERAL DE INTELIGENCIA Y POLÍ' )
            ( CveDir = '413040101'  Direccion = 'DIRECCIÓN DE ANÁLISIS TÁCTICO           ' )
            ( CveDir = '413040102'  Direccion = 'DIRECCIÓN DE ANÁLISIS CRIMINAL          ' )
            ( CveDir = '413040200'  Direccion = 'DIRECCIÓN GENERAL DE PREVENCIÓN SOCIAL D' )
            ( CveDir = '413040201'  Direccion = 'DIRECCIÓN DE PROGRAMAS DE PREVENCIÓN DEL' )
            ( CveDir = '413040202'  Direccion = 'DIRECCIÓN DE ATENCIÓN A VÍCTIMAS Y BÚSQU' )
            ( CveDir = '413050000'  Direccion = 'SUBSECRETARÍA DE DESARROLLO INSTITUCIONA' )
            ( CveDir = '413050100'  Direccion = 'DIRECCIÓN GENERAL DE CONTROL Y GESTIÓN D' )
            ( CveDir = '413050400'  Direccion = 'DIRECCIÓN GENERAL DE PLANEACIÓN Y EVALUA' )
            ( CveDir = '413050401'  Direccion = 'DIRECCIÓN DE PLANEACIÓN                 ' )
            ( CveDir = '413050402'  Direccion = 'DIRECCIÓN DE EVALUACIÓN                 ' )
            ( CveDir = '413060000'  Direccion = 'DIRECCIÓN GENERAL DE CONTROL DE TRÁNSITO' )
            ( CveDir = '413060100'  Direccion = 'DIRECCIÓN DE CIRCULACIÓN                ' )
            ( CveDir = '413060200'  Direccion = 'DIRECCIÓN DE SERVICIOS PERICIALES       ' )
            ( CveDir = '413070000'  Direccion = 'DIRECCIÓN GENERAL DE EMERGENCIA Y RESPUE' )
            ( CveDir = '413070100'  Direccion = 'DIRECCIÓN OPERATIVA                     ' )
            ( CveDir = '413070200'  Direccion = 'DIRECCIÓN DE TECNOLOGÍAS DE LA INFORMACI' )
            ( CveDir = '413080000'  Direccion = 'DIRECCIÓN DE PROTECCIÓN CIVIL           ' )
            ( CveDir = '413090000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '413100000'  Direccion = 'ACADEMIA DE FORMACIÓN Y PROFESIONALIZACI' )
            ( CveDir = '414000000'  Direccion = 'COORDINACIÓN GENERAL DE TRANSPARENCIA Y ' )
            ( CveDir = '414010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '414020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '414030000'  Direccion = 'UNIDAD DE SEGUIMIENTO DE ACCESO A LA INF' )
            ( CveDir = '414040000'  Direccion = 'UNIDAD DE OBLIGACIONES DE TRANSPARENCIA ' )
            ( CveDir = '414050000'  Direccion = 'UNIDAD DE GOBIERNO ABIERTO              ' )
            ( CveDir = '414060000'  Direccion = 'UNIDAD DE PROTECCIÓN DE DATOS PERSONALES' )
            ( CveDir = '414070000'  Direccion = 'UNIDAD JURÍDICA                         ' )
            ( CveDir = '416000000'  Direccion = 'SISTEMA MUNICIPAL DIF                   ' )
            ( CveDir = '417000000'  Direccion = 'ORGANISMO OPERADOR DEL SERVICIO DE LIMPI' )
            ( CveDir = '418000000'  Direccion = 'INSTITUTO MUNICIPAL DE ARTE Y CULTURA DE' )
            ( CveDir = '419000000'  Direccion = 'INSTITUTO MUNICIPAL DE PLANEACIÓN       ' )
            ( CveDir = '420000000'  Direccion = 'INSTITUTO MUNICIPAL DEL DEPORTE DE PUEBL' )
            ( CveDir = '421000000'  Direccion = 'INSTITUTO DE LA JUVENTUD DEL MUNICIPIO  ' )
            ( CveDir = '422000000'  Direccion = 'INDUSTRIAL DE ABASTOS DE PUEBLA         ' )
            ( CveDir = '424000000'  Direccion = 'COORDINACIÓN GENERAL DE COMUNICACIÓN SOC' )
            ( CveDir = '424010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '424020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '424030000'  Direccion = 'DIRECCIÓN DE ANÁLISIS GUBERNAMENTAL     ' )
            ( CveDir = '424040000'  Direccion = 'DIRECCIÓN DE MEDIOS DIGITALES Y DISEÑO  ' )
            ( CveDir = '424050000'  Direccion = 'DIRECCIÓN PRENSA E INFORMACIÓN          ' )
            ( CveDir = '424060000'  Direccion = 'UNIDAD DE ESTUDIOS  Y ESTRATEGIA        ' )
            ( CveDir = '424070000'  Direccion = 'UNIDAD JURÍDICA                         ' )
            ( CveDir = '426000000'  Direccion = 'SECRETARIA PARA LA IGUALDAD SUSTANTIVA  ' )
            ( CveDir = '426010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '426020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '426030000'  Direccion = 'DIRECCIÓN DE TRANSVERSALIDAD DE LA PERSP' )
            ( CveDir = '426040000'  Direccion = 'DIRECCIÓN DE PREVENCIÓN Y ATENCIÓN A LA ' )
            ( CveDir = '426050000'  Direccion = 'DIRECCIÓN DE IGUALDAD DE GÉNERO         ' )
            ( CveDir = '426060000'  Direccion = 'DIRECCIÓN DE SINERGIAS PARA LA IGUALDAD ' )
            ( CveDir = '426070000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '428000000'  Direccion = 'SECRETARÍA DE SERVICIOS PÚBLICOS        ' )
            ( CveDir = '428010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '428020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '428030000'  Direccion = 'DIRECCIÓN DE CALLES, PARQUES Y JARDINES ' )
            ( CveDir = '428040000'  Direccion = 'DIRECCIÓN DE  ALUMBRADO PÚBLICO Y SERVIC' )
            ( CveDir = '428050000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )
            ( CveDir = '429000000'  Direccion = 'SECRETARÍA DE MEDIO AMBIENTE            ' )
            ( CveDir = '429010000'  Direccion = 'SECRETARÍA PARTICULAR                   ' )
            ( CveDir = '429020000'  Direccion = 'SECRETARÍA TÉCNICA                      ' )
            ( CveDir = '429030000'  Direccion = 'DIRECCIÓN DE INFRAESTRUCTURA VERDE      ' )
            ( CveDir = '429040000'  Direccion = 'DIRECCIÓN DEL AGUA                      ' )
            ( CveDir = '429050000'  Direccion = 'DIRECCIÓN DE PROTECCIÓN ANIMAL          ' )
            ( CveDir = '429060000'  Direccion = 'DIRECCIÓN JURÍDICA                      ' )

         ).
         INSERT zt11tt_direccion FROM TABLE @IT_Direccion.
         if SY-subrc = 0.
              OUT->write( 'Se Inserta catalogo de Direcciones Correctamente' ).
         ELSE.
              OUT->write( 'Error al Insertar' ).
         ENDIF.
  ENDMETHOD.
ENDCLASS.
